# Generated by Django 4.0 on 2021-12-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='findings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='recommendations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
