# Generated by Django 4.0 on 2021-12-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_report_findings_alter_report_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
